<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <Version>0.5.0-p4</Version>
    <Authors>ARCHWALK</Authors>
    <Product>ARCHWALK</Product>
    <NeutralLanguage>ru</NeutralLanguage>
    <RhinoCommonVersion>8.25.25328.11001</RhinoCommonVersion>
  </PropertyGroup>
</Project>
